package project.model;
// Generated 19 mai 2016 02:33:48 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Matiere generated by hbm2java
 */
public class Matiere  implements java.io.Serializable {


     private Integer id;
     private Enseignant enseignant;
     private Groupe groupe;
     private String libelle;
     private float volumeCour;
     private float volumeTp;
     private float volumeTd;
     private float coefficient;
     private int credit;
     private Set<Note> notes = new HashSet<Note>(0);

    public Matiere() {
    }

	
    public Matiere(Enseignant enseignant, Groupe groupe, String libelle, float volumeCour, float volumeTp, float volumeTd, float coefficient, int credit) {
        this.enseignant = enseignant;
        this.groupe = groupe;
        this.libelle = libelle;
        this.volumeCour = volumeCour;
        this.volumeTp = volumeTp;
        this.volumeTd = volumeTd;
        this.coefficient = coefficient;
        this.credit = credit;
    }
    public Matiere(Enseignant enseignant,  Groupe groupe, String libelle, float volumeCour, float volumeTp, float volumeTd, float coefficient, int credit, Set<Note> notes) {
       this.enseignant = enseignant;
       this.groupe = groupe;
       this.libelle = libelle;
       this.volumeCour = volumeCour;
       this.volumeTp = volumeTp;
       this.volumeTd = volumeTd;
       this.coefficient = coefficient;
       this.credit = credit;
       this.notes = notes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Enseignant getEnseignant() {
        return this.enseignant;
    }

    public Groupe getGroupe() {
        return groupe;
    }

    public void setGroupe(Groupe groupe) {
        this.groupe = groupe;
    }
    
    public void setEnseignant(Enseignant enseignant) {
        this.enseignant = enseignant;
    }
   
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public float getVolumeCour() {
        return this.volumeCour;
    }
    
    public void setVolumeCour(float volumeCour) {
        this.volumeCour = volumeCour;
    }
    public float getVolumeTp() {
        return this.volumeTp;
    }
    
    public void setVolumeTp(float volumeTp) {
        this.volumeTp = volumeTp;
    }
    public float getVolumeTd() {
        return this.volumeTd;
    }
    
    public void setVolumeTd(float volumeTd) {
        this.volumeTd = volumeTd;
    }
    public float getCoefficient() {
        return this.coefficient;
    }
    
    public void setCoefficient(float coefficient) {
        this.coefficient = coefficient;
    }
    public int getCredit() {
        return this.credit;
    }
    
    public void setCredit(int credit) {
        this.credit = credit;
    }
    public Set<Note> getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set<Note> notes) {
        this.notes = notes;
    }




}


