package project.model;
// Generated 19 mai 2016 02:33:48 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Niveau generated by hbm2java
 */
public class Niveau  implements java.io.Serializable {


     private int id;
     private String libelle;
     private Set<Matiere> matieres = new HashSet<Matiere>(0);
     private Set<Groupe> groupes = new HashSet<Groupe>(0);

    public Niveau() {
    }

	
    public Niveau(String libelle) {
        this.libelle = libelle;
    }
    public Niveau(String libelle, Set<Matiere> matieres, Set<Groupe> groupes) {
       this.libelle = libelle;
       this.matieres = matieres;
       this.groupes = groupes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public Set<Matiere> getMatieres() {
        return this.matieres;
    }
    
    public void setMatieres(Set<Matiere> matieres) {
        this.matieres = matieres;
    }
    public Set<Groupe> getGroupes() {
        return this.groupes;
    }
    
    public void setGroupes(Set<Groupe> groupes) {
        this.groupes = groupes;
    }

    @Override
    public String toString() {
        return libelle;
    }

    
   



}


