package project.model;
// Generated 19 mai 2016 02:33:48 by Hibernate Tools 3.2.1.GA



/**
 * Note generated by hbm2java
 */
public class Note  implements java.io.Serializable {


     private Integer id;
     private Session session;
     private Matiere matiere;
     private Etudiant etudiant;
     private float noteTp;
     private float noteDs;
     private float noteExam;
     private float notePresence;
     private int numCompostage;

    public Note() {
    }

    public Note(Session session, Matiere matiere, Etudiant etudiant, float noteTp, float noteDs, float noteExam, float notePresence, int numCompostage) {
       this.session = session;
       this.matiere = matiere;
       this.etudiant = etudiant;
       this.noteTp = noteTp;
       this.noteDs = noteDs;
       this.noteExam = noteExam;
       this.notePresence = notePresence;
       this.numCompostage = numCompostage;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Session getSession() {
        return this.session;
    }
    
    public void setSession(Session session) {
        this.session = session;
    }
    public Matiere getMatiere() {
        return this.matiere;
    }
    
    public void setMatiere(Matiere matiere) {
        this.matiere = matiere;
    }
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }
    public float getNoteTp() {
        return this.noteTp;
    }
    
    public void setNoteTp(float noteTp) {
        this.noteTp = noteTp;
    }
    public float getNoteDs() {
        return this.noteDs;
    }
    
    public void setNoteDs(float noteDs) {
        this.noteDs = noteDs;
    }
    public float getNoteExam() {
        return this.noteExam;
    }
    
    public void setNoteExam(float noteExam) {
        this.noteExam = noteExam;
    }
    public float getNotePresence() {
        return this.notePresence;
    }
    
    public void setNotePresence(float notePresence) {
        this.notePresence = notePresence;
    }
    public int getNumCompostage() {
        return this.numCompostage;
    }
    
    public void setNumCompostage(int numCompostage) {
        this.numCompostage = numCompostage;
    }




}


