package project.model;
// Generated 19 mai 2016 02:33:48 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Session generated by hbm2java
 */
public class Session  implements java.io.Serializable {


     private Integer id;
     private String libelle;
     private Set<Note> notes = new HashSet<Note>(0);

    public Session() {
    }

	
    public Session(String libelle) {
        this.libelle = libelle;
    }
    public Session(String libelle, Set<Note> notes) {
       this.libelle = libelle;
       this.notes = notes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public Set<Note> getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set<Note> notes) {
        this.notes = notes;
    }




}


